# Generated by Django 4.1.3 on 2023-05-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0003_isharebundletransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isharebundletransaction',
            name='batch_id',
        ),
    ]
