# Generated by Django 4.1 on 2023-08-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0007_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
