# Generated by Django 5.0 on 2024-01-03 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0009_agentisharebundleprice_agentmtnbundleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='momo_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admininfo',
            name='payment_channel',
            field=models.CharField(choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Vodafone Cash', 'Vodafone Cash'), ('AT Money', 'AT Money')], default='MTN Mobile Money', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='isharebundletransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Initiated', 'Initiated'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Initiated', 'Initiated'), ('WIP', 'WIP'), ('Completed', 'Completed')], default='Pending', max_length=100),
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=250)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('credited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
