# Generated by Django 4.2.4 on 2024-01-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0011_alter_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='mtn_active',
            field=models.BooleanField(default=True),
        ),
    ]
