# Generated by Django 4.2.4 on 2024-04-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0012_admininfo_mtn_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='at_active',
            field=models.BooleanField(default=True),
        ),
    ]
